[[diagramParts]]
id = "esp"
type = "wokwi-esp32-devkit-v1"
attrs = {}

[[diagramParts]]
id = "dht1" 
type = "wokwi-dht22"
top = -15
left = 145

[[connections]]
from = "esp.gpio15"
to = "dht1.sd"

[[connections]]
from = "esp.3v3"
to = "dht1.vcc"

[[connections]]
from = "esp.gnd"
to = "dht1.gnd"

[[firmware]]
file = "esp32_sender.ino"